server:
  port: 8080

spring:
  application:
    name: identity-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

flyway:
  enabled: true
  baseline-on-migrate: true

jwt:
  secret: "replace_this_with_a_secure_base64_secret_key_in_production"
  expiration-ms: 86400000 # 24 hours
