plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':application')
    implementation project(':domain')
    implementation project(':shared')

    // Spring Boot Core & Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    
    // Data & Persistence
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    
    // Database Migration
    implementation 'org.flywaydb:flyway-core'
    
    // Database Driver
    runtimeOnly 'org.postgresql:postgresql'
    
    // Security & Cryptography
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.77'
    implementation 'de.mkammerer:argon2-jvm:2.11'
    
    // JWT
    implementation 'com.auth0:java-jwt:4.4.0'
    
    // Testing
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
